server:
  port: 8082
servers:
  camera-server: http://192.168.1.31
  auth-server: http://localhost:8080
  rest-server: http://localhost:8081
security:
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess