server:
  port: 8090
servers:
  camera1-server: http://localhost:8081
  camera2-server: http://localhost:8082
  auth-server: http://localhost:8083
  api-user-server: http://localhost:8083
  api-custom-server: http://localhost:8084
security:
  oauth2:
    client:
      client-id: beo-app-client
      client-secret: e6aec4e0-e421-415a-8f84-d06237963831